language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - "pip install markdown"

# command to run tests
script: python tools/lissie.py --source=./src --config=./tools/default.cfg --debug
